### ISSUE TITLE
Update recastai dependency

### ISSUE THREAD

**Issue by loulafripouille** [ouadie-lahdioui/botkit-middleware-recastai#3]
Hello,
It could be great to update recastai SDK dependency to the v3. Actually, this project is using the v2. Little changes are required in the code. 
Also, the response object have changed a bit, for instance, entities are note in an Array anymore but in an Object. But this requires only to update the readme.

What do you think? If you wish I could make a PR for that.

**Comment by ouadie-lahdioui** [comment]
Hello @laudeon,

Looks good to me 👍
